import { Router } from 'express';
import { loadStripePayments } from '../ingestion/stripe.js';
import { loadChargebeeSubscriptions } from '../ingestion/chargebee.js';
import { detectDuplicates } from '../reconciliation/deduplication.js';
import { join } from 'node:path';

export const reconciliationRouter = Router();

const DATA_DIR = join(process.cwd(), '../../data');

// In-memory store for discrepancies generated by the last run
let lastRunDiscrepancies: unknown[] = [];
let lastRunMeta: unknown = null;

reconciliationRouter.post('/run', async (_req, res) => {
  try {
    const startedAt = new Date().toISOString();

    const [stripePayments, chargebeeSubs] = await Promise.all([
      loadStripePayments(DATA_DIR),
      loadChargebeeSubscriptions(DATA_DIR),
    ]);

    const duplicates = await detectDuplicates(stripePayments, chargebeeSubs);

    // Convert duplicates to discrepancy format
    lastRunDiscrepancies = duplicates.map((d, i) => ({
      id: `disc_${i + 1}`,
      type: d.classification === 'true_duplicate' ? 'duplicate' : 'status_mismatch',
      severity: d.classification === 'true_duplicate' ? 'high' : 'medium',
      status: 'open',
      description: d.classification === 'true_duplicate'
        ? `Duplicate subscription detected: ${d.stripeRecord.customerName} exists in both Stripe and Chargebee with overlapping dates (${d.overlapDays} days overlap)`
        : `Possible migration: ${d.stripeRecord.customerName} -- Stripe ended before Chargebee started`,
      systemA: 'Stripe',
      systemB: 'Chargebee',
      valueA: `MRR: $${(d.stripeRecord.mrr / 100).toFixed(2)}`,
      valueB: `MRR: $${(d.chargebeeRecord.mrr / 100).toFixed(2)}`,
      delta: Math.abs(d.stripeRecord.mrr - d.chargebeeRecord.mrr) / 100,
      customerId: d.stripeRecord.customerId,
      detectedAt: startedAt,
      resolvedAt: null,
      resolutionNote: null,
      classification: d.classification,
      confidence: d.confidence.score,
      overlapDays: d.overlapDays,
    }));

    lastRunMeta = {
      runId: `run_${Date.now()}`,
      timestamp: startedAt,
      completedAt: new Date().toISOString(),
      totalRecords: stripePayments.length + chargebeeSubs.length,
      duplicatesFound: duplicates.length,
      trueDuplicates: duplicates.filter(d => d.classification === 'true_duplicate').length,
      migrations: duplicates.filter(d => d.classification === 'migration').length,
    };

    res.json({
      meta: lastRunMeta,
      discrepancies: lastRunDiscrepancies,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error('[reconciliation/run]', message);
    res.status(500).json({ error: message });
  }
});

reconciliationRouter.get('/discrepancies', (_req, res) => {
  res.json({
    data: lastRunDiscrepancies,
    meta: { total: lastRunDiscrepancies.length },
  });
});